# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/PFA_DOCKT_EHEI_2026
spring.datasource.username=postgres
spring.datasource.password=MarwaSou01@

# Hibernate (Pour voir les requêtes SQL dans la console IntelliJ)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ne pas modifier la base de données automatiquement (car vous l'avez déjà faite avec votre script SQL)
spring.jpa.hibernate.ddl-auto=update
# Changer le port du serveur
server.port=8080
server.error.include-message=always
